[theme]
base = "light"
primaryColor = "#0F8B8D"
backgroundColor = "#F6FAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#10233F"
font = "sans serif"

[server]
headless = true
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false